### ISSUE TITLE
Paths metadata field names not appearing correctly

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#122] opened 2019-10-18 05:06 UTC
The PATHS project metadata we added in this release is not appearing properly in the data subdomain web application.  See for example http://data.copticscriptorium.org/texts/pseudoephrem/letter-of-pseudo-ephrem-mercat-126-134/verses . Scroll down to metadata and the fields paths.works, paths.manuscripts, paths.authors are all now works, manuscripts, authors -- "paths." has been omitted.  

Is this a bug of some sort?  We need to post the metadata fields as paths.works, paths.manuscripts, paths.authors, as outlined in the PATHS project citation guidelines.  Amir and I emailed about this during the editing process. 

Can this be modified quickly?  It's important that we honor our collaborators' guidelines.  Thank you so much!  Please let me know if there is something I can do to help expedite.  Thank you!

**Comment by lgessler** [comment] 2019-10-21 03:25
I'm pretty sure I fixed the root cause of this bug in ff16038, I think I just must not have re-ingested this corpus. It'd be helpful if you could tell me the corpora which should have PATHS metadata. I'll take a look at this this week.

**Comment by ctschroeder** [comment] 2019-10-21 04:50
Hi. I tried to add it to all the new corpora from the last release plus some of the re-released, so pseudo.ephrem, dormition.john, johannes.canons, life.cyrus, life.longinus.lucius, life.onnophrius, proclus.homilies should all have the paths metadata.

Also, Amir and I discussed https://github.com/CopticScriptorium/corpora/issues/39 that there may be an issue with ANNIS.  I'm not sure fixing the bug in this web application will fix representation of the fieldname. Although, now that they're getting pulled from GitHub, maybe it will, come to think of it.

**Comment by lgessler** [comment] 2019-12-27 13:06
I confirmed just now that `addcorpus` works correctly, so now we just need to re-ingest every corpus. As you say, that ANNIS bug doesn't affect the website since we're pulling straight from GitHub now, so I'll do the reingest sometime soon.

**Comment by lgessler** [comment] 2019-12-28 01:13
OK, I reingested all the corpora that were added in 3.0 with their PATHS metadata, viz.:

* Life of Cyrus
* Life of Onnophrius
* Lives of Longinus and Lucius
* Martyrdom of Victor the General (part 2)
* Dormition of John
* Homilies of Proclus
* Letter of Pseudo-Ephrem

Once you confirm that these are the affected corpora and that the metadata is present we can close this issue.

**Comment by ctschroeder** [comment] 2020-01-02 00:43
@lgessler Did you ingest 3.0 or 3.0.1? There was an update 3.0.1

**Comment by lgessler** [comment] 2020-01-02 01:10
Whatever was in the master branch of the corpora repo when i commented 5 days ago. That would be 3.0.1 i presume?

**Comment by lgessler** [comment] 2020-01-02 13:09
Yeah, just checked, looks like 3.0.1 was released 2 months ago, so it was 3.0.1.

**Comment by ctschroeder** [comment] 2020-01-02 19:09
Thanks so much Luke!! 

Amir, I’ll follow up with PATHS about changing the field names since I know it just won’t work with ANNIS as is. It’s on my list but waiting for the holidays to pass.

**Closed** 2021-11-08 16:23 UTC
