### ISSUE TITLE
URN links not resolving

### ISSUE THREAD

**Issue by ctschroeder** [CopticScriptorium/cts#126] opened 2020-03-27 18:32 UTC
I know this is a difficult time, so apologies for posting.

I noticed today that the urn links don't all work.  For example http://data.copticscriptorium.org/urn:cts:copticLit:besa.aphthonia/ . This link is provided as one of the stable urls at the bottom of this page http://data.copticscriptorium.org/texts/besa_letters/to-aphthonia/.  However, clicking on the link produces an error. 

This is not a problem for http://data.copticscriptorium.org/urn:cts:copticLit:shenoute.abraham, however. 

Thanks for your help!

**Comment by lgessler** [comment] 2020-03-28 19:11
@amir-zeldes here are the relevant files:

- [`text.html`](https://github.com/CopticScriptorium/cts/blob/cc4b2c1cddca87856671e250177ff1009d3ddfd5/coptic/templates/text.html), where `text.edition_urn`, `text.corpus_urn`, and `text.textgroup_urn` are used
- [`views.py'](https://github.com/CopticScriptorium/cts/blob/cc4b2c1cddca87856671e250177ff1009d3ddfd5/coptic/coptic/views.py#L52L55): these attributes are populated there
- [`urn.py`](https://github.com/CopticScriptorium/cts/blob/cc4b2c1cddca87856671e250177ff1009d3ddfd5/coptic/texts/urn.py): contains logic for textgroup and corpus

@ctschroeder @amir-zeldes: the issue is that [when we construct a corpus urn](https://github.com/CopticScriptorium/cts/blob/cc4b2c1cddca87856671e250177ff1009d3ddfd5/coptic/texts/urn.py#L12), we: 

1. Base it on the document urn (e.g. urn:cts:copticLit:besa.aphthonia.monbba)
2. Modify the 4th colon-delimited piece (e.g. besa.aphthonia.monbba) by taking its first two period-delimited pieces and dropping the rest (e.g. besa.aphthonia)
3. Join the modified piece with the rest (e.g. urn:cts:copticLit:besa.aphthonia)

Here are some questions for both of you:

1. Is that corpus URN (urn:cts:copticLit:besa.aphthonia) sensible? If so, how should the URN resolver construct a corpus URN from a document URN?
2.

**Comment by ctschroeder** [comment] 2020-03-28 19:24
Hi. The naming conventions are not wrong. The corpus architecture is different.  After copticLit the namespaces are conventional-text-group.work.edition:divisions-of-work.  So Shenoute and Besa are traditional text groups because they are authors — all works by those authors are in that group. To Aphthonia and Abraham Our father are both works, hence “Abraham” and “Aphthonia” in that name space.

Corpus architecture that didn’t conform with the URNs was a known issue during the original construction of this software. I don’t remember the reasoning, but back then we chose not to change the corpus architecture. It took a while to get it right, but programmer Dave figured it out back in the day. 

Fundamentally: the software needs to return the correct documents for all those name spaces.  I’m not a programmer, so I can’t tell you how to do it. I can just say this could be an issue for a LOT of documents, since the urns and corpus architecture are not aligned for all corpora.

The URNs are not wrong.

**Comment by ctschroeder** [comment] 2020-03-28 19:24
Sorry I couldn’t give you an easy solution!  The solution will have to be in the programming.

**Comment by lgessler** [comment] 2020-03-28 19:40
Right, it's the structure of the corpora that's the issue. OK, I think I understand now. A couple more questions:

- What did http://data.copticscriptorium.org/urn:cts:copticLit:shenoute link to back in the old interface? Was it a list of all corpora associated with Shenoute?
- In the text view, the caption "Author Textgroup" is odd when the group is not a person--e.g. "Author Textgroup: urn:cts:copticLit:lives". Perhaps we should make the caption "Text Group:" instead?

**Comment by ctschroeder** [comment] 2020-03-28 22:10
http://data.copticscriptorium.org/urn:cts:copticLit:shenoute  linked to all documents with that part of the URN. 

You don’t need to return “corpora”—just docs with matching urns in those namespaces.

**Comment by ctschroeder** [comment] 2020-03-28 22:11
We also can eliminate some of those links below if you want, or instead of saying “corpus” urn, say text group, etc.

**Comment by ctschroeder** [comment] 2020-03-28 22:48
this function of resolving URNS is supposed to be the primary function of this app—everything else is bells and whistles.  These urns are the stable identifiers people use to cite texts and texts groups; they can come here and then find the text cited in an article, book, etc. this is a critical feature. They should return every item with a matching urn for those namespaces.

**Comment by ctschroeder** [comment] 2020-03-28 22:49
Lmk if you want a phone call @lgessler

**Comment by lgessler** [comment] 2020-03-29 00:04
That's probably a good idea so we can make sure we've ironed out every detail. @amir-zeldes let's try to schedule one?

**Comment by amir-zeldes** [comment] 2020-03-29 01:33
Sounds like a plan - my preference BTW would be to fold all the necessary information into the corpora themselves, i.e. introduce a corpus level URN metadatum, and the same for corpus title behavior, which is currently configured in the repo but is not actually in the data. We can talk more about it when we meet.

**Comment by lgessler** [comment] 2020-03-31 18:00
Summary of the meeting:

*Problems*
- URN resolution only accepts exact matches
- Corpora have different structures which is reflected in their URN: 
`urn:cts:copticLit:johannes.canons`has pieces after `copticLit` whereas `urn:cts:copticLit:besa` has one.
- The "Text Corpus" and "Author Textgroup" are valid CTS URNs but in light of the problem above it is not clear which one ought to serve as the Coptic Scriptorium corpus URN

*Solutions*
1. URN resolution should work by exact-matching URN pieces left-to-right, returning any document that exactly matches all the pieces in the query URN
2. Corpora need to have their corresponding URNs `manually` provided as a metadatum, and supporting work will need to be done in the code to use this.
3. "Text Corpus" should be renamed to "Work" and "Author Textgroup" to "Textgroup"

**Comment by lgessler** [comment] 2020-03-31 18:03
@amir-zeldes @ctschroeder if a corpus doesn't have a manually listed metadatum, should we not provide any "official" Coptic Scriptorium URN, or should we assume that it's something, where that something could be either the "Work" URN (2 pieces) or the "Textgroup" URN (1 piece)?

**Comment by ctschroeder** [comment] 2020-03-31 18:05
I think we need to go in and add the corpus metadata to all corpora and issue a new release.  @amir-zeldes am I correct on the steps? is this something Lance can do using the manifest already online?

**Comment by amir-zeldes** [comment] 2020-03-31 19:41
Yes, I think this should be straightforward. I'm OK with the ingest failing if the corpus doesn't have the expected field, that will just remind us that the corpus metadata is incomplete. But I would not make a new release for it now, it can wait for the next release (since currently each corpus has a manually entered and correct field there, and the software needs to be adapted to include this information from the github download)

**Comment by ctschroeder** [comment] 2020-03-31 22:29
Ok I thought perhaps Luke's changes would break something without the corpus URN  in there. If nothing will break if Luke goes ahead without them, I'll add an issue to GitHub and our next release schedule for Lance to add this corpus metadatum field and info, and we can just roll them out on our usual cycle?

**Comment by ctschroeder** [comment] 2020-03-31 22:31
Also I already did 3 on [Luke's list](https://github.com/CopticScriptorium/cts/issues/126#issuecomment-606783243) and made a pull request #129

**Comment by ctschroeder** [comment] 2020-04-15 18:44
Hi. How is this going? Anything I can do to help? Thanks!

**Comment by lgessler** [comment] 2020-04-20 00:25
Hi, sorry--it's the end of the semester and I still haven't had a spare chunk of hours to get this done. I'm hoping I'll be able to get to it this week.

**Comment by ctschroeder** [comment] 2020-04-25 00:49
Thanks @lgessler I get it!

**Comment by ctschroeder** [comment] 2020-06-18 20:12
hi has this been fixed? I saw some activity last month. Thanks so much for all the work on it.

**Comment by lgessler** [comment] 2020-06-18 20:42
The fix is developed (#130), I'm waiting for @amir-zeldes to OK it

**Comment by amir-zeldes** [comment] 2020-06-19 15:53
Sorry about that - I had used the GitHub 'review' functionality but missed a second stage OK button and didn't do 'submit review'. I just had one question about it, see in #130

**Comment by lgessler** [comment] 2020-06-22 20:01
@ctschroeder changes are live in production, please have a look when you have a moment

**Comment by amir-zeldes** [comment] 2020-06-23 19:29
Looks good to me, thanks! @ctschroeder feel free to close if this looks good to you.

**Comment by ctschroeder** [comment] 2020-06-23 22:42
The current URNs I tested are working well. Thank you!

It looks like the handful of obsolete URNs (see old issue #112 fixed some months ago) no longer redirect. Any way to re-implement that fix from #112?  Thanks!

**Comment by lgessler** [comment] 2020-06-23 22:55
Which URNs exactly are you trying? [`urn:cts:copticLit:shenoute.abraham.monbya_525_530`](http://data.copticscriptorium.org/urn:cts:copticLit:shenoute.abraham.monbya_525_530) and others from that issue. work fine for me.

**Comment by ctschroeder** [comment] 2020-06-23 22:58
That's odd, because I cut and pasted the URN in your comment into the box and got this error: 
No results found for urn:cts:copticLit:shenoute.abraham.monbya_525_530 in any field with (document_cts_urn matching urn:cts:copticLit:shenoute.abraham.monbya_525_530). Please try a different query

http://data.copticscriptorium.org/search?text=+urn%3Acts%3AcopticLit%3Ashenoute.abraham.monbya_525_530

**Comment by ctschroeder** [comment] 2020-06-23 23:00
(Of course the message is accurate: there is no item with that entry in that field. But the functionality is supposed to be that the obsolete URNs will return the correct items. It's a short list of documents.)

**Comment by ctschroeder** [comment] 2020-06-24 23:40
@lgessler did you see my comment and do you have any questions? thx

**Comment by amir-zeldes** [comment] 2020-06-25 16:52
I think the misunderstanding is that @lgessler is saying the redirect does work from URLs like this:

http://data.copticscriptorium.org/urn:cts:copticLit:shenoute.abraham.monbya_525_530

But @ctschroeder is pointing out that searching in the box for the URN string doesn't:

urn:cts:copticLit:shenoute.abraham.monbya_525_530

**Comment by ctschroeder** [comment] 2020-06-25 17:32
Thanks. Yes that seems to be what is going on. Previously, before the last big update, typing the string into the box worked. I'm hoping this isn't too much work for you to reimplement. Thank you so much @lgessler . Apologies if I wasn't clear or was a bit abrupt -- not my intent at all!

**Comment by lgessler** [comment] 2020-06-25 20:06
Oh got it, fixed in #132. Seems to be working now in prod, please have a look.

**Comment by amir-zeldes** [comment] 2020-06-25 20:24
Works like a charm, thanks @lgessler !

**Closed by amir-zeldes** 2020-06-25 20:24 UTC
Labels: bug

**Comment by ctschroeder** [comment] 2020-06-26 01:41
Yay! Thank you so much!
